export const BASE_URL = "http://95.216.184.20:9000";

export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";

export const GET_ONE_DATA_REQUEST = "GET_ONE_DATA_REQUEST";
export const GET_ONE_DATA_SUCCESS = "GET_ONE_DATA_SUCCESS";
export const GET_ONE_DATA_FAIL = "GET_ONE_DATA_FAIL";

export const POST_USER_DATA_REQUEST = "POST_USER_DATA_REQUEST";
export const POST_USER_DATA_SUCCESS = "POST_USER_DATA_SUCCESS";
export const POST_USER_DATA_FAIL = "POST_USER_DATA_FAIL";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const POST_ORDERS_REQUEST = "POST_ORDERS_REQUEST";
export const POST_ORDERS_SUCCESS = "POST_ORDERS_SUCCESS";
export const POST_ORDERS_FAIL = "POST_ORDERS_FAIL";
export const POST_ORDERS_CLEAR = "POST_ORDERS_CLEAR";

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL";
export const MY_ORDERS_CLEAR = "MY_ORDERS_CLEAR"

export const GET_ONE_ORDER_REQUEST = "GET_ONE_ORDER_REQUEST";
export const GET_ONE_ORDER_SUCCESS = "GET_ONE_ORDER_SUCCESS";
export const GET_ONE_ORDER_FAIL = "GET_ONE_ORDER_FAIL";
export const ONE_ORDER_CLEAR = "ONE_ORDER_CLEAR"

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE = "INCREASE";
export const DECREASE = "DECREASE";
export const CHECKOUT = "CHECKOUT";
export const CLEAR = "CLEAR";

export const SORT_LIST_SWITCH = "SORT_LIST_SWITCH";

export const DARK_MODE_SWITCH = "DARK_MODE_SWITCH";

